---
keys:
  - https://brave-browser-apt-release.s3.brave.com/brave-core.asc
flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
flatpaks:
  - remote: flathub
    packages:
      - com.getpostman.Postman
      - com.skype.Client
packages:
  - brave-browser
  - build-essential
  - com.github.donadigo.appeditor
  - com.github.ronnydo.colorpicker
  - com.github.stsdc.monitor
  - elementary-tweaks
  - ffmpeg
  - firefox
  - flatpak
  - lsb
  - neovim
  - net-tools
  - ntp
  - openssh-server
  - silversearcher-ag
  - software-properties-common
  - sudo
  - tar
  - tig
  - tmux
  - tzdata
  - wget
  - xsel
removed_packages:
  - epiphany-browser
  - epiphany-browser-data
  - epiphany-browser-data
  - epiphany-extensions
repositories:
  - deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
  - ppa:neovim-ppa/stable
  - ppa:philip.scott/elementary-tweaks
timezone: Europe/Warsaw
