---
keys:
  - https://dl.google.com/linux/linux_signing_key.pub
  - https://download.sublimetext.com/sublimehq-pub.gpg
flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
debs:
  - https://github.com/duplicati/duplicati/releases/download/v2.0.6.100-2.0.6.100_canary_2021-08-11/duplicati_2.0.6.100-1_all.deb
  - https://github.com/twpayne/chezmoi/releases/download/v2.7.5/chezmoi_2.7.5_linux_amd64.deb
flatpaks:
  - remote: flathub
    packages:
      - com.getpostman.Postman
      - com.microsoft.Teams
      - com.spotify.Client
      - com.transmissionbt.Transmission/x86_64/stable
packages:
  - apt-transport-https
  - build-essential
  - cryptsetup
  - ecryptfs-utils
  - google-chrome-stable
  - gnome-tweaks
  - gparted
  - gthumb
  - ffmpeg
  - firefox
  - flatpak
  - lsb
  - net-tools
  - ntp
  - openssh-server
  - papirus-icon-theme
  - peek
  - ripgrep
  - software-properties-common
  - steam
  - sublime-text
  - sudo
  - tar
  - tig
  - tmux
  - tzdata
  - wget
  - vim-gtk # supports clipboard
  - xsel
removed_packages:
  - eog
  - vim
repositories:
  - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  - deb https://download.sublimetext.com/ apt/stable/
  - ppa:neovim-ppa/unstable
  - ppa:papirus/papirus
  - ppa:peek-developers/stable
timezone: Europe/Warsaw
