---
keys:
  - https://dl.google.com/linux/linux_signing_key.pub
flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
debs:
  - https://updates.duplicati.com/beta/duplicati_2.0.5.1-1_all.deb
flatpaks:
  - remote: flathub
    packages:
      - com.getpostman.Postman
      - com.microsoft.Teams
      - com.skype.Client
      - com.spotify.Client
packages:
  - build-essential
  - cryptsetup
  - ecryptfs-utils
  - google-chrome-stable
  - gnome-tweaks
  - gparted
  - gthumb
  - ffmpeg
  - firefox
  - flatpak
  - lsb
  - neovim
  - net-tools
  - ntp
  - openssh-server
  - papirus-icon-theme
  - peek
  - silversearcher-ag
  - software-properties-common
  - sudo
  - tar
  - tig
  - tmux
  - tzdata
  - wget
  - xsel
removed_packages:
  - eog
repositories:
  - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  - ppa:neovim-ppa/stable
  - ppa:papirus/papirus
  - ppa:peek-developers/stable
timezone: Europe/Warsaw
