---
flatpaks:
  - remote: flathub
    packages:
      - com.skype.Client
      - com.visualstudio.code
packages:
  - build-essential
  - chrome-gnome-shell
  - chromium-browser
  - elementary-tweaks
  - flat-remix
  - flatpak
  - gparted
  - htop
  - lsb
  - neovim
  - net-tools
  - ntp
  - openssh-server
  - openssl
  - pantheon-mail
  - patch
  - papirus-icon-theme
  - silversearcher-ag
  - software-properties-common
  - sudo
  - tar
  - tig
  - tmux
  - tree
  - tzdata
  - unzip
  - wget
  - xsel
removed_packages:
  - epiphany-browser
  - epiphany-browser-data
  - epiphany-browser-data
  - epiphany-extensions
repositories:
  - ppa:daniruiz/flat-remix
  - ppa:neovim-ppa/stable
  - ppa:papirus/papirus
  - ppa:philip.scott/elementary-tweaks
timezone: Europe/Warsaw
