---
- hosts: all
  roles:
    - packages
    - gpu
    - drivers
    - development
    - security
  become: no
  vars:
    gpu: amd
  pre_tasks:
    - name: Get upstream name
      shell: lsb_release -ucs
      register: lsb_name
