---
- name: System upgrade
  apt:
    upgrade: safe
    update-cache: yes

- name: Add keys
  apt_key:
    url: "{{item}}"
    state: present
  with_items: "{{keys}}"
  when: keys is defined

- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items: "{{repositories}}"

- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}"

- name: Remove default flatpak
  package:
    name: flatpack
    state: absent

- name: Install latest flatpak
  apt:
    name: flatpak
    default_release: bionic

- name: Add flatpak remotes
  flatpak_remote:
    name: "{{item.key}}"
    flatpakrepo_url: "{{item.value}}"
    state: present
  with_dict: "{{remotes}}"

- name: Install flatpak apps
  flatpak:
    name: "{{item.1}}"
    remote: "{{item.0.remote}}"
    state: present
  with_subelements:
    - "{{flatpaks}}"
    - "names"

- name: Configure time zone
  command: "timedatectl set-timezone {{ timezone }}"

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
