---
- name: System upgrade
  apt:
    autoremove: yes
    upgrade: dist
    update-cache: yes
  become: yes

- name: Add keys
  apt_key:
    url: "{{item}}"
    state: present
  become: yes
  with_items: "{{keys}}"
  when: keys is defined

- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  become: yes
  with_items: "{{repositories}}"

- name: Remove packages
  package:
    name: "{{item}}"
    state: absent
  become: yes
  with_items: "{{removed_packages}}"

- name: Install new packages
  package:
    name: "{{item}}"
    state: latest
    install_recommends: no
  become: yes
  with_items: "{{packages}}"
  when: packages is defined

- name: Install new debs
  apt:
    deb: "{{item}}"
  become: yes
  with_items: "{{debs}}"
  when: debs is defined

- name: Add flatpak repos
  flatpak_remote:
    name: "{{item.name}}"
    flatpakrepo_url: "{{item.url}}"
    state: present
  become: yes
  with_items: "{{flatpak_repos}}"
  when: flatpak_repos is defined

- name: Update all flatpaks to their latest version
  shell: flatpak update --noninteractive
  become: yes

- name: Install flatpak apps
  flatpak:
    name: "{{item.1}}"
    remote: "{{item.0.remote}}"
    state: present
  become: yes
  with_subelements:
    - "{{flatpaks}}"
    - "packages"
  when: flatpaks is defined

- name: Configure time zone
  command: "timedatectl set-timezone {{ timezone }}"
  become: yes

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
  become: yes
