---
- name: Stop ssh daemon
  service:
    name: ssh
    state: stopped
  become: yes

- name: Secure SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "#?PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no" }
  become: yes

- name: Start ssh daemon
  service:
    name: ssh
    state: started
  become: yes
