---
anyenv_url: https://github.com/anyenv/anyenv.git
anyenv_updater_url: https://github.com/znz/anyenv-update.git
anyenv_plugins:
  - nodenv
  - rbenv
keys:
  - https://download.docker.com/linux/ubuntu/gpg
  - https://www.postgresql.org/media/keys/ACCC4CF8.asc
mkcert_url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64
packages:
  - cmake
  - containerd.io
  - curl
  - direnv
  - docker-ce
  - docker-ce-cli
  - git
  - imagemagick
  - jq
  - libmagickwand-dev
  - libncurses5-dev
  - libpq-dev
  - openssl
  - postgresql-client-9.6
  - postgresql-client-10
  - postgresql-client-11
  - postgresql-client-12
  - shellcheck
removed_packages:
  - containerd
  - docker
  - docker-engine
  - docker.io
  - runc
repositories:
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_name.stdout}} stable"
  - "deb http://apt.postgresql.org/pub/repos/apt {{lsb_name.stdout}}-pgdg main"
