---
anyenv_url: https://github.com/anyenv/anyenv.git
anyenv_updater_url: https://github.com/znz/anyenv-update.git
anyenv_plugins:
  - exenv
  - nodenv
  - rbenv
keys:
  - http://deb.tableplus.com/apt.tableplus.com.gpg.key
  - https://cli-assets.heroku.com/apt/release.key
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
  - https://packages.microsoft.com/keys/microsoft.asc
packages:
  - bat
  - cmake
  - code
  - curl
  - direnv
  - docker-ce
  - docker-ce-cli
  - erlang
  - git
  - git-lfs
  - heroku
  - imagemagick
  - jq
  - libmagickwand-dev
  - libmediainfo-dev
  - libncurses5-dev
  - libpq-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - openssl
  - shellcheck
  - tableplus
removed_packages:
  - containerd
  - docker
  - docker-engine
  - docker.io
  - runc
repositories:
  - deb [arch=amd64] https://deb.tableplus.com/debian tableplus main
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_name.stdout}} stable
  - deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
  - deb https://cli-assets.heroku.com/apt ./
  - deb https://packages.erlang-solutions.com/ubuntu {{lsb_name.stdout}} contrib
