---
anyenv_url: https://github.com/anyenv/anyenv.git
anyenv_updater_url: https://github.com/znz/anyenv-update.git
anyenv_plugins:
  - nodenv
  - rbenv
keys:
  - http://deb.tableplus.com/apt.tableplus.com.gpg.key
  - https://cli-assets.heroku.com/apt/release.key
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
  - https://www.postgresql.org/media/keys/ACCC4CF8.asc
mkcert_url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64
packages:
  - cmake
  - containerd.io
  - curl
  - direnv
  - docker-ce
  - docker-ce-cli
  - fzf
  - git
  - git-lfs
  - heroku
  - imagemagick
  - jq
  - libmagickwand-dev
  - libncurses5-dev
  - libpq-dev
  - libreadline-dev
  - libssl-dev
  - openssl
  - postgresql-client-10
  - postgresql-client-11
  - postgresql-client-12
  - postgresql-client-13
  - postgresql-client-9.6
  - shellcheck
  - tableplus
removed_packages:
  - containerd
  - docker
  - docker-engine
  - docker.io
  - runc
repositories:
  - deb [arch=amd64] https://deb.tableplus.com/debian tableplus main
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_name.stdout}} stable
  - deb http://apt.postgresql.org/pub/repos/apt {{lsb_name.stdout}}-pgdg main
  - deb https://cli-assets.heroku.com/apt ./
  - deb https://packages.erlang-solutions.com/ubuntu {{lsb_name.stdout}} contrib
