---
- name: Create fonts directory
  file:
    path: "{{ansible_env.HOME}}/.local/share/fonts"
    state: directory

- name: Install fonts
  get_url:
    url: "{{item}}"
    dest: "{{ansible_env.HOME}}/.local/share/fonts"
  with_items: "{{fonts}}"
