---
- name: Tweak gtk styles
  copy:
    src: gtk.css
    dest: "{{ansible_env.HOME}}/.config/gtk-3/gtk.css"

- name: Restart wingpanel
  shell: killall wingpanel

- name: Download Qogir icon pack
  git:
    repo: https://github.com/vinceliuice/Qogir-icon-theme.git
    dest: "{{code_path}}/src/github.com/vinceliuice/Qogir-icon-theme"
    depth: 1

- name: Install Qogir icons
  shell: "./install.sh"
  args:
    chdir: "{{code_path}}/src/github.com/vinceliuice/Qogir-icon-theme"

- name: Download Gogh (terminal themes)
  git:
    repo: https://github.com/Mayccoll/Gogh.git
    dest: "{{code_path}}/src/github.com/Mayccoll/Gogh"
    depth: 1
