---
- name: Update docker config
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  become: yes

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: "{{ansible_env.USER}}"
    append: yes
    groups: docker
  become: yes

- name: Restart Docker
  service:
    name: docker
    state: restarted
  become: yes
