---
- name: Add keys
  apt_key:
    url: "{{item}}"
    state: present
  become: yes
  with_items: "{{keys}}"
  when: keys is defined

- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  become: yes
  with_items: "{{repositories}}"

- name: Remove packages
  package:
    name: "{{item}}"
    state: absent
  become: yes
  with_items: "{{removed_packages}}"

- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  become: yes
  with_items: "{{packages}}"

- name: Install packages from URLs
  unarchive:
    src: "{{item}}"
    dest: "/usr/local/bin"
    mode: '0755'
    remote_src: True
  become: yes
  with_items: "{{remote_packages}}"

- name: Ensure bash_profile is loaded from bashrc
  blockinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    block: |
      if [ -f $HOME/.bash_profile ]; then
        source $HOME/.bash_profile
      fi

- name: Increase inotify limits
  blockinfile:
    dest: "/etc/sysctl.conf"
    insertafter: EOF
    block: |
      fs.inotify.max_user_watches=524288
  notify: reload sysctl.conf
  become: yes

- include: anyenv.yml
- include: docker.yml
- include: databases.yml
