---
- name: Install common lib packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{libs}}"

- name: Check if asdf installed
  stat:
    path: "~/.asdf"
  become: no
  register: asdf

- name: Install asdf
  shell: "git clone {{asdf_url}} ~/.asdf --branch {{asdf_branch}}"
  become: no
  when: asdf.stat.exists == False

- name: Update asdf
  shell: "~/.asdf/bin/asdf update"
  become: no
  when: asdf.stat.exists == True

- name: Install asdf plugins
  shell: "~/.asdf/bin/asdf plugin add {{item}}"
  become: no
  with_items: "{{asdf_plugins}}"

- name: Install mkcert
  get_url:
    url: "{{mkcert_url}}"
    dest: /usr/local/bin/mkcert
    mode: '0755'
