---
- name: Add keys
  apt_key:
    url: "{{item}}"
    state: present
  become: yes
  with_items: "{{keys}}"
  when: keys is defined

- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  become: yes
  with_items: "{{repositories}}"

- name: Remove packages
  package:
    name: "{{item}}"
    state: absent
  become: yes
  with_items: "{{removed_packages}}"

- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  become: yes
  with_items: "{{packages}}"

- name: Install mkcert
  get_url:
    url: "{{mkcert_url}}"
    dest: /usr/local/bin/mkcert
    mode: '0755'
  become: yes

- name: Ensure bash_profile is loaded from bashrc
  blockinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    block: |
      if [ -f $HOME/.bash_profile ]; then
        source $HOME/.bash_profile
      fi

- include: anyenv.yml
- include: docker.yml
- include: databases.yml
