---
- name: Remove packages
  package:
    name: "{{item}}"
    state: absent
  with_items: "{{removed_packages}}"

- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}"

- name: Disable iptables for Docker
  lineinfile:
    dest: /etc/default/docker
    regexp: "^#?DOCKER_OPTS"
    line: "DOCKER_OPTS=\"--dns 8.8.8.8 --dns 8.8.4.4 --iptables=false\""

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Check if anyenv installed
  stat:
    path: "~/.anyenv"
  become: no
  register: anyenv

- name: Install anyenv
  shell: "git clone {{anyenv_url}} ~/.anyenv"
  become: no
  when: anyenv.stat.exists == False

- name: Install anyenv updater
  shell: "git clone {{anyenv_updater_url}} ~/.anyenv/plugins/anyenv-update"
  become: no
  when: anyenv.stat.exists == False

- name: Initialize anyenv
  shell: "~/.anyenv/bin/anyenv install --init"
  become: no
  when: anyenv.stat.exists == Fale

- name: Install anyenv plugins
  shell: "~/.anyenv/bin/anyenv install {{item}}"
  become: no
  ignore_errors: yes
  with_items: "{{anyenv_plugins}}"

- name: Update anyenv
  shell: "~/.anyenv/bin/anyenv update"
  become: no

- name: Install mkcert
  get_url:
    url: "{{mkcert_url}}"
    dest: /usr/local/bin/mkcert
    mode: '0755'
