---
- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items: "{{repositories}}.{{driver}}"

- name: Install drivers
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}.{{driver}}"
