---
- name: Add driver repositories
  apt_repository:
    repo: "{{item.1}}"
    state: present
  with_subelements:
    - "{{repositories}}"
    - "sources"
  when: "item.0.driver in drivers"

- name: Create drivers directory
  file:
    path: "/tmp/drivers"
    state: directory

- name: Install driver debs
  apt:
    deb: "{{item}}"
    state: present
  with_fileglob:
    - "/tmp/drivers/*.deb"

- name: Install driver packages
  package:
    name: "{{item.1}}"
    state: latest
  with_subelements:
    - "{{packages}}"
    - "names"
  when: "item.0.driver in drivers"
