---
- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}"

- name: Clone logiops
  git:
    repo: https://github.com/PixlOne/logiops.git
    dest: "{{ansible_env.HOME}}/Code/src/github.com/PixlOne/logiops"

- name: Create logiops build directory
  file:
    path: "{{ansible_env.HOME}}/Code/src/github.com/PixlOne/logiops/build"
    state: directory

- name: Build logiops
  shell: cmake .. && make
  args:
    chdir: "{{ansible_env.HOME}}/Code/src/github.com/PixlOne/logiops/build"

- name: Install logiops
  shell: make install
  args:
    chdir: "{{ansible_env.HOME}}/Code/src/github.com/PixlOne/logiops/build"
  become: yes
