---
- name: Add gpu driver repositories
  apt_repository:
    repo: "{{item.1}}"
    state: present
  become: yes
  with_subelements:
    - "{{repositories}}"
    - "sources"
  when: "gpu is defined and item.0.brand == gpu"

- name: Create gpu drivers directory
  file:
    path: "/tmp/gpu"
    state: directory
  when: gpu is defined

- name: Install gpu driver debs
  apt:
    deb: "{{item}}"
    state: present
  become: yes
  with_fileglob:
    - "/tmp/gpu/*.deb"
  when: gpu is defined

- name: Remove gpu driver directory
  file:
    path: "/tmp/gpu"
    state: absent
  when: gpu is defined

- name: Install gpu driver packages
  package:
    name: "{{item.1}}"
    state: latest
  become: yes
  with_subelements:
    - "{{packages}}"
    - "names"
  when: "gpu is defined and item.0.brand == gpu"
